// Generated by https://quicktype.io

export interface GiveawayBody {
    title:             string;
    description:       string;
    giveawayDate:      string;
    participantsLimit: number;
    // image
}
