// Generated by https://quicktype.io

export interface DiscordUserRes {
    id:                     string;
    username:               string;
    avatar:                 null;
    discriminator:          string;
    public_flags:           number;
    premium_type:           number;
    flags:                  number;
    banner:                 null;
    accent_color:           null;
    global_name:            string;
    avatar_decoration_data: null;
    banner_color:           null;
    mfa_enabled:            boolean;
    locale:                 string;
    email:                  string;
    verified:               boolean;
}
